services:
  server:
    build:
      context: ./server
    container_name: umra-server
    environment:
      UMRA_ANALYZERS_PCPTRC_ONLINE_FORWARDING_ENABLED: "true"
    ports:
      - "8080:8080"

  client:
    build:
      context: ./client
    container_name: umra-client
    depends_on:
      - server
    ports:
      - "4173:4173"