spring:
  graphql:
    graphiql:
      enabled: false
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"

server:
  port: 8080

umra:
  analyzers:
    pcptrc:
      online-forwarding-enabled: true
